name: Deploy docs
on:
  push:
    branches:
      - main
      - alpha

jobs:
  release:
    name: deploy docs
    if: github.repository == 'node-real/greenfield-toolkit'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Build docs
        run: pnpm build:docs

      - name: Redirect
        run: |
          mkdir -p ./docs/dist/docs/dist
          cat << EOF > "./docs/dist/docs/dist/index.html"
            <script>window.location.href='https://github.com/node-real/greenfield-toolkit/packages/uploadkit</script>
          EOF

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/dist
          branch: 'docs'
          clean: true
          force: true
